sudo: false
language: python
before_install:
- openssl aes-256-cbc -K $encrypted_c58512e35a45_key -iv $encrypted_c58512e35a45_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mkdir -p lib
install:
- pip install -r requirements.txt -t lib/
script:
- echo ""
deploy:
  provider: gae
  keyfile: bricks-build-docs-75cfd3f6946f.json
  project: bricks-build-docs
  skip_cleanup: true
  default: true
