application: travis-github-doc-builder
version: v11
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: .*  # This regex directs all routes to main.app
  script: main.app

libraries:
- name: yaml
  version: "3.10"