#application: bricks-build-docs
version: v11
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: .*  # This regex directs all routes to main.app
  script: main.app

libraries:
- name: yaml
  version: "3.10"